/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:02f9a837-58de-4894-9c15-247ea42524ed",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_LPvLh73FB",
    "aws_user_pools_web_client_id": "6v25umr967gp1a7scaem4d1us1",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "bookstorev22410c604b9a641448e349eb27d9c88a385802-prod",
    "aws_user_files_s3_bucket_region": "us-east-2",
    "aws_appsync_graphqlEndpoint": "https://xcntffgx3jbnfdblqoe3aezsqa.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-ywan2vbwsnc5vjrldagtujdv4e",
    "aws_content_delivery_bucket": "bookstorev2-20230403105349-hostingbucket-prod",
    "aws_content_delivery_bucket_region": "us-east-2",
    "aws_content_delivery_url": "http://bookstorev2-20230403105349-hostingbucket-prod.s3-website.us-east-2.amazonaws.com"
};


export default awsmobile;
